import type { Metadata } from "next";
import { Fraunces, Inter, Tiro_Devanagari_Hindi } from "next/font/google";
import "./globals.css";
import { LocaleProvider } from "@/lib/locale";
import { AudioPreferenceProvider } from "@/lib/audio";
import { site } from "@/content/site";
import { musicSchoolJsonLd, jsonLdScript } from "@/lib/seo";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const tiro = Tiro_Devanagari_Hindi({
  subsets: ["devanagari", "latin"],
  weight: "400",
  variable: "--font-tiro",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — Music, Dance & Fine Arts in Karvi, Chitrakoot`,
    template: `%s · ${site.shortName}`,
  },
  description: site.description,
  keywords: [
    "music classes Karvi",
    "music school Chitrakoot",
    "singing classes Chitrakoot",
    "tabla sitar guitar classes",
    "Kathak dance classes Karvi",
    "Bundelkhand folk dance",
    "vocal classes Uttar Pradesh",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: site.locale,
    url: site.url,
    siteName: site.name,
    title: `${site.name} — Music, Dance & Fine Arts`,
    description: site.description,
    // OG image auto-generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: site.name,
    description: site.description,
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${inter.variable} ${tiro.variable}`}>
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(musicSchoolJsonLd()) }}
        />
        <LocaleProvider>
          <AudioPreferenceProvider>{children}</AudioPreferenceProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
